f = open("text.txt", "w", encoding="utf8")
f.write("안녕하세요")
f.write("\n")
f.write("반갑습니다.")
f.write("\n")
f.close()

f = open("text.txt", "r", encoding="utf8")
str = f.read()
print(str)
print("----")
f.close()

f = open("text.txt", "r", encoding="utf8")
line1 = f.readline()
print("Line1 : ", line1)
line2 = f.readline()
print("Line2 : ", line2)
line3 = f.readline()
print("Line3 : ", line3)
f.close()